// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/18/2026, 5:20:07 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/popcorn/Desktop/hry webiste/hry-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/popcorn/Desktop/hry webiste/hry-nuxt/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/popcorn/Desktop/hry webiste/hry-nuxt/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/popcorn/Desktop/hry webiste/hry-nuxt/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/popcorn/Desktop/hry webiste/hry-nuxt/plugins/**/*.{js,ts,mjs}","/Users/popcorn/Desktop/hry webiste/hry-nuxt/composables/**/*.{js,ts,mjs}","/Users/popcorn/Desktop/hry webiste/hry-nuxt/utils/**/*.{js,ts,mjs}","/Users/popcorn/Desktop/hry webiste/hry-nuxt/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/popcorn/Desktop/hry webiste/hry-nuxt/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/popcorn/Desktop/hry webiste/hry-nuxt/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/popcorn/Desktop/hry webiste/hry-nuxt/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;